### ISSUE TITLE
removing users from UI creates ghost TAs

### ISSUE THREAD

**Issue by mdehghanim** [USC-CSSL/Automatic-TA-assignment#33]
The users are not completely deleted from the system. Specifically, their preferences still remain active, and this causes the match to fail.

**Comment by kaurrajdeep** [comment]
Estimate : 2 hr
Test all possible cases from UI.

**Comment by kaurrajdeep** [comment]
Remove data from all tables related to User (TA, TA_Preferences, TA_Time_Constraints).

Done as part of Similar to https://github.com/USC-CSSL/Automatic-TA-assignment/issues/35

**Comment by kaurrajdeep** [comment]
Changes pushed.

**Comment by mdehghanim** [comment]
This bug is still there. I deleted a user, and then ran the matching algorithm. See attached
<img width="1082" alt="screen shot 2018-06-11 at 5 08 59 pm" src="https://user-images.githubusercontent.com/6384236/41263193-3028a056-6d9a-11e8-8066-50b882502977.png">

**Comment by kaurrajdeep** [comment]
Hi,
 Was the algorithm matching not deleted before re-run? 
 Also, I haven't deleted entries of Matching when user is deleted. Is it required?
Regards,
Rajdeep

**Comment by mdehghanim** [comment]
I reran the matching after deleting the user. The algorithm match was not deleted first. Should I do that first?

**Comment by mdehghanim** [comment]
I ran the matching algorithm, and it doesn't run

**Comment by kaurrajdeep** [comment]
Hi,
 I have corrected it. The sql call was not made.

Regards,
Rajdeep

**Comment by mdehghanim** [comment]
Works now. Thank you
